IF DB_Id('SoapFormula') IS NULL
CREATE DATABASE SoapFormula
GO

USE SoapFormula

IF (NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'Products'))
CREATE TABLE Products(
	Id INT IDENTITY NOT NULL PRIMARY KEY,
	Name VARCHAR(20) NOT NULL,
	Price MONEY NOT NULL,
	Weight INT NOT NULL)

IF (NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'Categories'))
CREATE TABLE Categories( 
	Id INT IDENTITY NOT NULL PRIMARY KEY,
	Name VARCHAR(20) NOT NULL)

IF (NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'ProductsCategories'))
CREATE TABLE ProductsCategories(
	ProductId INT NOT NULL CONSTRAINT FK_ProductsCategories_Products_ProductId FOREIGN KEY REFERENCES Products(Id),
	CategoryId INT NOT NULL CONSTRAINT FK_ProductsCategories_Categories_CategoryId FOREIGN KEY REFERENCES Categories(Id),
	PRIMARY KEY (ProductId, CategoryId))

IF (NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'Files'))
CREATE TABLE Files(
	Id INT IDENTITY NOT NULL PRIMARY KEY,
	Url VARCHAR(20) NOT NULL,
	ProductId INT NOT NULL CONSTRAINT FK_Files_Products_ProductId FOREIGN KEY REFERENCES Products(Id))


	
	
	