USE SoapFormula

IF (NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'Manufacturers'))
CREATE TABLE Manufacturers(
	Id INT IDENTITY NOT NULL PRIMARY KEY,
	Name VARCHAR(20) NOT NULL)
	
IF (NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'dbo' AND TABLE_SCHEMA = 'Products'
AND COLUMN_NAME = 'ManufacturerId'))
	ALTER TABLE Products 
	ADD ManufacturerId INT NOT NULL 
	CONSTRAINT FK_Products_Manufacturers_ManufacturerId
	FOREIGN KEY REFERENCES Manufacturers(Id)